baseURL = "https://www.runink.org/"
title = "Runink"
theme = "hextra"

# Site Settings

[services]
  [services.googleAnalytics]
    ID = 'G-SEECKDWZNJ'
enableRobotsTXT = true
enableGitInfo = true
hasCJKLanguage = false
defaultContentLanguage = "en"

# Languages

[languages]
[languages.en]
languageName = "English"
weight = 1

[markup]
[markup.highlight]
noClasses = false
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.extensions.passthrough]
  delimiters = { block = [["\\[", "\\]"], ["$$", "$$"]], inline = [["\\(", "\\)"]] }

enable = true

enableInlineShortcodes = true

# Outputs

[outputs]
home = ["HTML"]
page = ["HTML"]
section = ["HTML", "RSS"]

# Menus

[menu]
[[menu.main]]
identifier = "docs"
name = "Documentation"
pageRef = "/docs"
weight = 1
[[menu.main]]
identifier = "usecases"
name = "Use Cases"
pageRef = "/use-cases"
weight = 2
[[menu.main]]
identifier = "whitepapers"
name = "Technical Whitepapers"
pageRef = "/whitepapers"
weight = 3
[[menu.main]]
identifier = "blog"
name = "Blog"
pageRef = "/blog"
weight = 4
[[menu.main]]
identifier = "contact"
name = "Contact"
pageRef = "/contact"
weight = 5
[[menu.main]]
identifier = "services"
name = "Professional Services"
pageRef = "/services"
weight = 6

# Parameters

[params]
description = "Runink: Your Go-to Hub for for orchestrating secure, testable, and governance-driven data pipelines at scale. Fitting your Cloud, Data Engineering, and Generative AI initiatives with secure solutions, and cutting-edge compliant technologies."

showVisitedLinks = false
disableBreadcrumb = true
disableNextPrev = true
disableTopNavigation = true
ordersectionsby = "weight"
logo = "images/logo.png"
themeVariantToggle = true

[params.navbar]
displayTitle = true
displayLogo = true
logo = { path = "images/logo.png", dark = "images/logo_white.png" }
width = "wide"

[params.page]
width = "normal"

[params.theme]
default = "system"
displayToggle = true

[params.footer]
enable = true
displayCopyright = true
displayPoweredBy = true
width = "normal"

displayUpdatedDate = true
dateFormat = "January 2, 2006"

[params.search]
enable = true
type = "flexsearch"
[params.search.flexsearch]
index = "content"
tokenize = "forward"

[params.editURL]
  enable = true
  base = "https://github.com/runink-site/docs/edit/main/content"

[params.blog]
[params.blog.list]
displayTags = true
sortBy = "date"
sortOrder = "desc"
[params.blog.article]
displayPagination = true

[params.toc]
displayTags = true

[params.highlight.copy]
enable = true
display = "hover"

[params.comments]
enable = false

# Permalinks

[permalinks]
blog = "/blog/:year/:month/:day/:contentbasename/"

