baseURL = "https://runink.org/"
title = "Runink"
theme = "relearn"
defaultContentLanguage = "en"
enableGitInfo = true
enableEmoji = true

[params]
  mermaidZoom = true
  mermaid.force = true
  themeVariant = "green"                          # Choose theme variant: green, blue, red, etc.
  showVisitedLinks = false
  disableBreadcrumb = true
  disableNextPrev = true
  disableTopNavigation = true
  ordersectionsby = "weight"
  logo = "images/logo.png"
  themeVariantToggle = true
  
[menu]

  [[menu.sidebar]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.sidebar]]
    name = "Documentation"
    url = "/docs/"
    weight = 2

  [[menu.sidebar]]
    name = "Forums"
    url = "/forums/"
    weight = 3

[[menu.shortcuts]]
name = "GitHub"
url = "https://github.com/paesdan/runink"
weight = 1
pre = "<i class='fab fa-github'></i> "

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      attribute = true
