@startuml
!theme materia
skinparam linetype ortho
skinparam componentStyle rectangle

actor "Client" as Client #E6E6FA

rectangle "HERD CONTROL PLANE" {
  interface "API (gRPC/REST)" as Api
  component "API Server" as ApiServer #D9D9D9
  component "Scheduler" #98FB98
  component "Secrets Mgr" #DDA0DD
  component "RBAC Mgr" #DDA0DD
  component "DataGov" #DDA0DD
  database "Barn (Raft Store + Checkpoints)" as Barn #D8BFD8

  Api --> ApiServer
  ApiServer --> Barn
  ApiServer --> Scheduler
  ApiServer --> [Secrets Mgr]
  ApiServer --> [RBAC Mgr]
  ApiServer --> DataGov
  Scheduler --> Barn
  [Secrets Mgr] --> Barn
  DataGov --> Barn

  note right of Barn
    Raft-backed:
    - Strong consistency
    - Checkpoint metadata
    - Quotas, RBAC, lineage
  end note
}

rectangle "Worker Node" {
  component "runi-agent" as Agent #AFEEEE
  component "Runi Slice" as Slice #90EE90
  database "Checkpoint (Btrfs)" as Snap #E5F5E0

  Agent --> Slice : Launch / Isolate
  Slice --> Agent : Logs / Metrics
  Agent --> Snap : Save / Restore
  Agent --> [Secrets Mgr]
  Agent --> DataGov
  Slice --> DataGov : Lineage
  "Scheduler" --> Agent : Recovery Cmd
  Barn --> Agent : Pull Snapshot Metadata
}

Client --> Api
@enduml
