name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive     # ✅ ensures theme (Relearn) is included
          fetch-depth: 0

      - name: Update submodules manually (safety)
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.127.0'   # ✅ compatible with Relearn
          extended: true

      - name: Build Hugo site
        env:
          HUGO_ENV: production
        run: |
          hugo --minify --baseURL "https://paesdan.github.io/runink-site/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
